var digraph_details = ['digraph G {',
 ' rankdir  = "LR";',
 ' label    = "Tech Tree of OATMEAL Projects";',
 ' labelloc = "t";',
 ' node [style=filled,',
 '       color="black", ',
 '       fontcolor="white", ',
 '       shape="oval", ',
 '       fixedsize=true, ',
 '       width=2,',
 '       height=2];',
 ' ',
 ' potPaper [label="A Plane of Thrones\nPaper"];',
 ' robPaper [label="Robotics Papers"];',
 ' deskSenseDn [label="Below Desk Sensing"];',
 ' desks [label="Unit Desks"];',
 ' deskSenseUp [label="Above Desk Sensing"];',
 ' mApp [label="Mobile App"];',
 ' geoEthno2 [label="Geographic/\nEthnographic data 2"];',
 ' basicBeacon [label="iBeacon Awareness"];',
 ' sensicorn2 [label="Sensicorn 2"];',
 ' geoEthno1 [label="Geographic/\nEthnographic data 1"];',
 ' emailData [label="Email Data"];',
 ' RBTM [label="Robotic Building\nTopology Modification"];',
 ' basicRobot [label="Awareness of Robots"];',
 ' timeData [label="Timesheet Data"];',
 ' SNA [label="Social Network\nAnalysis"];',
 ' changeSpace [label="Change Space\nCollective"];',
 ' robDesk [label="Robotic Desk\nArrangement"];',
 ' Shakedown [label="Shakedown data\ncapture"];',
 ' SNAawareness [label="SNA Awareness"];',
 ' phone [label="Access To Phones"];',
 ' halo [label="Robotic Weaving"];',
 ' SNAblog [label="Social Network\nAnalysis Blog Post"];',
 ' SydStudioSeating [label="Sydney Studio Seating"];',
 ' revit2ML [label="Revit Layout\nExtraction"];',
 ' data [label="Data Literacy"];',
 ' sensicorn1 [label="Sensicorn 1"];',
 ' SydStudioSeating2 [label="Better Sydney Studio\nSeating"];',
 ' diary [label="Diary Studies"];',
 ' SLAM [label="SLAM (Simultanious\nLocation And Mapping)"];',
 ' bravo [label="Bravo Victor November"];',
 ' pot [label="A Plane of Thrones\nFramework"];',
 ' deskLoc [label="Desk Location"];',
 ' electron [label="Desktop App"];',
 ' robSense [label="Robot Mounted Sensing"];',
 ' boom [label="Distribution Boom"];',
 ' altSpace [label="altSpace"];',
 ' AIlayout [label="AI Layout"];',
 ' lAmp [label="Learning Amplified\nSeating Plans"];',
 ' bizCap [label="Capturing Business\nMetrics"];',
 ' loTraining [label="Layout Training Data"];',
 ' cadd [label="Continuous Analysis,\nDesign & Delivery"];',
 ' geoEthno3 [label="Geographic/\nEthnographic data 3"];',
 ' ShakedownPaper [label="Shakedown Paper"];',
 ' s3 [label="S3"];',
 ' sensors [label="Sensor Literacy"];',
 ' pathVis [label="Path Visualisation"];',
 ' lExp [label="Learning Experiment"];',
 ' systemReef [label="Systems Reef"];',
 ' ShakedownBlog [label="Shakedown Blog"];',
 ' Shakedown2 [label="Shakedown (with\nstalls) Product"];',
 ' hardware [label="Hardware Design"];',
 ' BTARATA [label="Buildings That Are\nRight All The Time"];',
 ' pot -> potPaper;',
 ' revit2ML -> potPaper;',
 ' halo -> robPaper;',
 ' electron -> deskSenseUp;',
 ' s3 -> deskSenseUp;',
 ' phone -> mApp;',
 ' geoEthno1 -> geoEthno2;',
 ' deskSenseDn -> geoEthno2;',
 ' mApp -> sensicorn2;',
 ' sensicorn1 -> sensicorn2;',
 ' deskLoc -> geoEthno1;',
 ' deskSenseUp -> geoEthno1;',
 ' diary -> geoEthno1;',
 ' robDesk -> RBTM;',
 ' emailData -> SNA;',
 ' timeData -> SNA;',
 ' AIlayout -> robDesk;',
 ' lAmp -> robDesk;',
 ' robSense -> robDesk;',
 ' sensors -> Shakedown;',
 ' basicRobot -> halo;',
 ' bravo -> SNAblog;',
 ' pot -> SydStudioSeating;',
 ' hardware -> sensicorn1;',
 ' pathVis -> sensicorn1;',
 ' lAmp -> SydStudioSeating2;',
 ' SydStudioSeating -> SydStudioSeating2;',
 ' electron -> diary;',
 ' basicBeacon -> deskLoc;',
 ' desks -> deskLoc;',
 ' basicRobot -> robSense;',
 ' sensors -> robSense;',
 ' SLAM -> robSense;',
 ' systemReef -> boom;',
 ' loTraining -> AIlayout;',
 ' lExp -> lAmp;',
 ' pot -> lAmp;',
 ' SNA -> lAmp;',
 ' bizCap -> cadd;',
 ' geoEthno3 -> cadd;',
 ' RBTM -> cadd;',
 ' sensicorn2 -> geoEthno3;',
 ' geoEthno2 -> geoEthno3;',
 ' Shakedown -> ShakedownPaper;',
 ' hardware -> s3;',
 ' sensors -> s3;',
 ' data -> sensors;',
 ' revit2ML -> lExp;',
 ' Shakedown -> Shakedown2;',
 ' cadd -> BTARATA;',
 ' {rank = same; data; basicRobot; hardware; systemReef; SNAawareness}',
 ' \n}']

 digraph_details =  digraph_details.join("\n");
