var digraph_details = ['digraph G {',
 ' rankdir  = "LR";',
 ' label    = "Tech Tree of OATMEAL Projects";',
 ' labelloc = "t";',
 ' node [style=filled,',
 '       color="black", ',
 '       fontcolor="white", ',
 '       shape="oval", ',
 '       fixedsize=true, ',
 '       width=2,',
 '       height=2,',
 '       fontsize=8 ',
 '      ];',
 ' ',
 ' potPaper [label="A Plane of\nThrones Paper"];',
 ' robPaper [label="Robotics Papers"];',
 ' deskSenseDn [label="Below Desk\nSensing"];',
 ' desks [label="Unit Desks"];',
 ' deskSenseUp [label="Above Desk\nSensing"];',
 ' mApp [label="Mobile App"];',
 ' geoEthno2 [label="Geographic/\nEthnographic\ndata 2"];',
 ' basicBeacon [label="iBeacon\nAwareness"];',
 ' sensicorn2 [label="Sensicorn 2"];',
 ' geoEthno1 [label="Geographic/\nEthnographic\ndata 1"];',
 ' emailData [label="Email Data"];',
 ' RBTM [label="Robotic\nBuilding\nTopology\nModification"];',
 ' basicRobot [label="Awareness of\nRobots"];',
 ' timeData [label="Timesheet Data"];',
 ' SNA [label="Social Network\nAnalysis"];',
 ' changeSpace [label="Change Space\nCollective"];',
 ' robDesk [label="Robotic Desk\nArrangement"];',
 ' Shakedown [label="Shakedown data\ncapture"];',
 ' SNAawareness [label="SNA Awareness"];',
 ' phone [label="Access To\nPhones"];',
 ' halo [label="Robotic Weaving"];',
 ' SNAblog [label="Social Network\nAnalysis Blog\nPost"];',
 ' SydStudioSeating [label="Sydney Studio\nSeating"];',
 ' revit2ML [label="Revit Layout\nExtraction"];',
 ' data [label="Data Literacy"];',
 ' sensicorn1 [label="Sensicorn 1"];',
 ' SydStudioSeating2 [label="Better Sydney\nStudio Seating"];',
 ' diary [label="Diary Studies"];',
 ' SLAM [label="SLAM\n(Simultanious\nLocation And\nMapping)"];',
 ' bravo [label="Bravo Victor\nNovember"];',
 ' pot [label="A Plane of\nThrones\nFramework"];',
 ' deskLoc [label="Desk Location"];',
 ' electron [label="Desktop App"];',
 ' robSense [label="Robot Mounted\nSensing"];',
 ' boom [label="Distribution\nBoom"];',
 ' altSpace [label="altSpace"];',
 ' AIlayout [label="AI Layout"];',
 ' lAmp [label="Learning\nAmplified\nSeating Plans"];',
 ' bizCap [label="Capturing\nBusiness\nMetrics"];',
 ' loTraining [label="Layout Training\nData"];',
 ' cadd [label="Continuous\nAnalysis,\nDesign &\nDelivery"];',
 ' geoEthno3 [label="Geographic/\nEthnographic\ndata 3"];',
 ' ShakedownPaper [label="Shakedown Paper"];',
 ' s3 [label="S3"];',
 ' sensors [label="Sensor Literacy"];',
 ' pathVis [label="Path\nVisualisation"];',
 ' lExp [label="Learning\nExperiment"];',
 ' systemReef [label="Systems Reef"];',
 ' ShakedownBlog [label="Shakedown Blog"];',
 ' Shakedown2 [label="Shakedown (with\nstalls) Product"];',
 ' hardware [label="Hardware Design"];',
 ' BTARATA [label="Buildings That\nAre Right All\nThe Time"];',
 ' ',
 ' pot -> potPaper;',
 ' revit2ML -> potPaper;',
 ' halo -> robPaper;',
 ' boom -> desks;',
 ' halo -> desks;',
 ' s3 -> deskSenseUp;',
 ' phone -> mApp;',
 ' geoEthno1 -> geoEthno2;',
 ' deskSenseDn -> geoEthno2;',
 ' sensicorn2 -> geoEthno2;',
 ' sensicorn1 -> sensicorn2;',
 ' mApp -> sensicorn2;',
 ' deskSenseUp -> geoEthno1;',
 ' diary -> geoEthno1;',
 ' deskLoc -> geoEthno1;',
 ' robDesk -> RBTM;',
 ' timeData -> SNA;',
 ' emailData -> SNA;',
 ' SNAawareness -> SNA;',
 ' geoEthno1 -> changeSpace;',
 ' AIlayout -> robDesk;',
 ' lAmp -> robDesk;',
 ' robSense -> robDesk;',
 ' sensors -> Shakedown;',
 ' basicRobot -> halo;',
 ' systemReef -> halo;',
 ' SNA -> SNAblog;',
 ' bravo -> SNAblog;',
 ' lExp -> SydStudioSeating;',
 ' deskLoc -> SydStudioSeating;',
 ' pathVis -> sensicorn1;',
 ' hardware -> sensicorn1;',
 ' SydStudioSeating -> SydStudioSeating2;',
 ' electron -> diary;',
 ' basicRobot -> SLAM;',
 ' basicBeacon -> deskLoc;',
 ' desks -> deskLoc;',
 ' SLAM -> robSense;',
 ' sensors -> robSense;',
 ' systemReef -> boom;',
 ' geoEthno2 -> altSpace;',
 ' loTraining -> AIlayout;',
 ' lExp -> lAmp;',
 ' SNA -> lAmp;',
 ' pot -> lAmp;',
 ' revit2ML -> loTraining;',
 ' geoEthno3 -> cadd;',
 ' RBTM -> cadd;',
 ' bizCap -> cadd;',
 ' geoEthno2 -> geoEthno3;',
 ' Shakedown -> ShakedownPaper;',
 ' hardware -> s3;',
 ' desks -> s3;',
 ' sensors -> s3;',
 ' data -> sensors;',
 ' Shakedown -> ShakedownBlog;',
 ' bravo -> ShakedownBlog;',
 ' Shakedown -> Shakedown2;',
 ' cadd -> BTARATA;',
 ' {rank = same; data; basicRobot; hardware; systemReef; SNAawareness}',
 ' \n}'];


 digraph_details =  digraph_details.join("\n");
